name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Compile TypeScript
        run: npm run compile
      
      - name: Package extension
        run: npm run package
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.vsix
          body: |
            ## Radium v${{ steps.get_version.outputs.VERSION }}
            
            ### Installation
            
            Download the `.vsix` file below and install it in VS Code:
            
            **Method 1: VS Code UI**
            1. Open VS Code
            2. Go to Extensions view (Cmd/Ctrl+Shift+X)
            3. Click the `...` menu at the top
            4. Select "Install from VSIX..."
            5. Choose the downloaded `.vsix` file
            
            **Method 2: Command Line**
            ```bash
            code --install-extension radium-${{ steps.get_version.outputs.VERSION }}.vsix
            ```
            
            ### What's Changed
            
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
            
            ### Requirements
            
            - VS Code ^1.85.0 or later
            
            ### Support
            
            - 📖 [Documentation](https://github.com/${{ github.repository }}/tree/main/docs)
            - 🐛 [Report Issues](https://github.com/${{ github.repository }}/issues)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

